# -*- coding: utf-8 -*-

development:
  adapter: postgresql
  encoding: utf8
  database: todoptec_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: todoptec_tst
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: da4gl8v6naboh3
  host: ec2-23-21-91-29.compute-1.amazonaws.com
  pool: 5
  username: grjhprrkddknvq
  password: QW_9YZHKao_Y-x3l3lUyH1juxQ