# -*- coding: utf-8 -*-

development:
  adapter: postgresql
  encoding: utf8
  database: todoptec_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: todoptec_tst
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: todoptec_prd
  host: localhost
  pool: 5
  username: postgres
  password: postgres